@extends('layouts.admin')
@section('title','تنظیمات سایت') @section('heading','تنظیمات سایت') @section('eyebrow','Identity, content & SEO')
@section('content')<form class="admin-form" method="POST" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
@foreach(collect($definitions)->groupBy('group') as $group=>$items)<section class="admin-panel admin-form-section"><div class="admin-panel-heading"><div><p>Settings</p><h2>{{ $group }}</h2></div></div><div class="admin-input-grid">
@foreach($items as $key=>$definition)
@if($definition['type']==='textarea')<label class="admin-input-span"><span>{{ $definition['label'] }}</span><textarea name="{{ $key }}" rows="4">{{ old($key,$values[$key] ?? '') }}</textarea></label>
@elseif($definition['type']==='boolean')<div class="admin-input-span"><input type="hidden" name="{{ $key }}" value="0"><label class="admin-checkbox"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$values[$key] ?? '0')==='1')><span>{{ $definition['label'] }}</span></label></div>
@elseif(in_array($definition['type'],['image','file']))<label class="admin-input-span"><span>{{ $definition['label'] }}</span>@if($values[$key] ?? null)<a class="admin-current-file" href="{{ Storage::url($values[$key]) }}" target="_blank">مشاهده فایل فعلی ↗</a><input type="hidden" name="remove_{{ $key }}" value="0"><label class="admin-checkbox"><input type="checkbox" name="remove_{{ $key }}" value="1"><span>حذف فایل فعلی</span></label>@endif<input type="file" name="{{ $key }}" @if($definition['type']==='image') accept="image/png,image/jpeg,image/webp" @else accept="application/pdf" @endif></label>
@else<label><span>{{ $definition['label'] }}</span><input type="{{ in_array($definition['type'],['email','url']) ? $definition['type']:'text' }}" name="{{ $key }}" value="{{ old($key,$values[$key] ?? '') }}" @if($definition['type']==='url') dir="ltr" @endif></label>@endif
@endforeach</div></section>@endforeach<div class="admin-sticky-actions"><button class="admin-primary-button" type="submit">ذخیره تنظیمات</button></div></form>@endsection