@extends('layouts.admin')
@section('title','مدیریت مهارت‌ها')
@section('heading','مهارت‌ها')
@section('eyebrow','Capabilities')
@section('content')
<div class="admin-two-column">
<section class="admin-panel admin-form-section"><div class="admin-panel-heading"><div><p>New skill</p><h2>افزودن مهارت</h2></div></div><form method="POST" action="{{ route('admin.skills.store') }}" class="admin-form">@csrf
<label><span>نام *</span><input type="text" name="name" required></label><label><span>دسته *</span><input type="text" name="category" value="Development" required></label><div class="admin-input-grid"><label><span>برچسب کوتاه</span><input type="text" name="short_label" maxlength="12"></label><label><span>تسلط</span><input type="number" name="proficiency" min="1" max="100"></label><label><span>ترتیب</span><input type="number" name="sort_order" value="0" min="0" required></label></div><input type="hidden" name="is_published" value="0"><label class="admin-checkbox"><input type="checkbox" name="is_published" value="1" checked><span>نمایش در سایت</span></label><button class="admin-primary-button" type="submit">افزودن</button></form></section>
<section class="admin-panel"><div class="admin-panel-heading"><div><p>Skills</p><h2>فهرست مهارت‌ها</h2></div><span>{{ $skills->count() }}</span></div><div class="admin-skill-list">
@forelse($skills as $item)<article class="admin-skill-card"><form method="POST" action="{{ route('admin.skills.update',$item) }}" class="admin-form">@csrf @method('PUT')<div class="admin-input-grid"><label><span>نام</span><input type="text" name="name" value="{{ $item->name }}" required></label><label><span>دسته</span><input type="text" name="category" value="{{ $item->category }}" required></label><label><span>برچسب</span><input type="text" name="short_label" value="{{ $item->short_label }}"></label><label><span>تسلط</span><input type="number" name="proficiency" value="{{ $item->proficiency }}" min="1" max="100"></label><label><span>ترتیب</span><input type="number" name="sort_order" value="{{ $item->sort_order }}" min="0" required></label></div><input type="hidden" name="is_published" value="0"><label class="admin-checkbox"><input type="checkbox" name="is_published" value="1" @checked($item->is_published)><span>منتشر</span></label><button class="admin-secondary-button" type="submit">ذخیره</button></form><form method="POST" action="{{ route('admin.skills.destroy',$item) }}" data-confirm="این مهارت حذف شود؟">@csrf @method('DELETE')<button class="admin-danger-link" type="submit">حذف</button></form></article>@empty<p class="admin-empty">مهارتی وجود ندارد.</p>@endforelse
</div></section></div>
@endsection
